In [ ]:
# pip install numpy

  Using cached numpy-2.2.5-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.5-cp312-cp312-win_amd64.whl (12.6 MB)


# this is numpy class

In [3]:
import numpy as np

In [5]:
# Python List
list_example = [ 1,"hello", 2,3,4,5]
list_example

[1, 'hello', 2, 3, 4, 5]

In [6]:
# numpy array
array_example = np.array([1,2,3,4,5,6], dtype = np.int32)
array_example

array([1, 2, 3, 4, 5, 6])

In [7]:
array2= np.array([1,"hello",3.5])
array2

array(['1', 'hello', '3.5'], dtype='<U32')

In [8]:
# array3= np.array([1,"hello",3.5], dtype= np.int32)

In [9]:
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [10]:
print(a.shape)
print(a[0])
a[0] = 4
print(a)

(3,)
1
[4 2 3]


In [11]:
b= np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [12]:
print(b.shape)

(2, 2)


In [13]:
b.ndim

2

In [14]:
arr = np.array([[[1,2],[3,4]],
                [[5,6],[7,8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
arr.ndim

3

In [16]:
b= np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b[0:2]
# b[0:2,0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# c[1:3,1:3]
c[1:3,1:4]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [20]:
row_r1 = c[1,:]
row_r2 = c[1:2,:]
row_r3 = c[[1],:]

print(row_r1, row_r1.shape, row_r1.ndim)
print(row_r2, row_r2.shape, row_r2.ndim)
print(row_r3, row_r3.shape, row_r3.ndim)


[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2
[[5 6 7 8]] (1, 4) 2


In [21]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [22]:
b= np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [23]:
c = np.full((2,2),2)
print(c)
print(c.dtype)

[[2 2]
 [2 2]]
int32


In [24]:
d = np.eye(2)
print(d)
print(d.dtype)

[[1. 0.]
 [0. 1.]]
float64


### vstack() or row_stack()  and hstack or column_stack()

In [25]:
x= np.array([1,2,3])
y= np.array([4,5,6])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
x= np.array([[1],[2],[3]])
y= np.array([[4],[5],[6]])
print(x)
print(y)
np.hstack((x,y))

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [2]:
x= np.array([[1,2],[3,4]], dtype = np.float64)
y= np.array([[5,6],[7,8]], dtype = np.float64)

print(x + y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [3]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [4]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [5]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [6]:
print(np.square(x,y))

[[ 1.  4.]
 [ 9. 16.]]


In [7]:
v = np.array([9,10])
w = np.array([11,12])


print(v.dot(w))
print(np.dot(v,w))

219
219


In [9]:
print(np.dot(x,v))
print(x@v)

[29. 67.]
[29. 67.]


In [14]:
np.cross(x,y)

array([ 2., 12.])

In [23]:
preds = np.array([0.2, 0.5, 0.92, 0.9, 0.1])
predicted_class_index = np.argmax(preds)
predicted_class_index

2

In [ ]:
to_predict_class = ["apple", "banana", "ball", "mango", "orange"]
predicted_class_index = np.where(preds > .85)[0]

for possible_class_index in predicted_class_index:
    print(to_predict_class[possible_class_index])

In [ ]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])
# get the index of thr maximum element in a
# {this array has two elements with the maximum value
# only returns one index}

print(np.argmax(a))

2


In [25]:
print(np.argmin(a))

3


In [27]:
# set sorted list of index
print (a)
print(np.sort(a))
print(np.argsort(a))

[ 1  8  9 -3  2  4  7  9]
[-3  1  2  4  7  8  9  9]
[3 0 4 5 6 1 2 7]


In [30]:
x= np.array([[1,2],[3,4],[5,6]])

print(np.max(x))
print(np.min(x))
print(np.sum(x))

6
1
21


In [36]:
x = np.array([[1,2,8],[4,5,6],[4,6,5]])

print(np.max(x, axis=0))
print(np.max(x, axis=1))

[4 6 8]
[8 6 6]


In [37]:
arr = np.array([1,2])
arr.T

array([1, 2])

In [39]:
a =np.array([[1,2],[3,4],[5,6]])

print(a)
print("Transpose\n", a.T)

[[1 2]
 [3 4]
 [5 6]]
Transpose
 [[1 3 5]
 [2 4 6]]


# reshape class


In [5]:
data = np.array([1,2,3,4,5,6,7,8])
data.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
data.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [11]:
w = np.array([[1],[2],[3]])
print(w)
w.shape

[[1]
 [2]
 [3]]


(3, 1)

In [13]:
y = w.reshape(-1)
print(y)
y.shape

[1 2 3]


(3,)

#### squeeze()
#### used to remove single dimensions

In [14]:
w = np.array([[1],[2],[3]])
z= w.squeeze()
print(z)
z.shape

[1 2 3]


(3,)

In [17]:
arr = np.array([[1],[2]])
print(arr.shape)
arr2 = np.array([[[1],[2]]])
print(arr2.shape)



(2, 1)
(1, 2, 1)


In [19]:
squeeze_arr2= np.squeeze(arr2)
print(squeeze_arr2.shape)
print(squeeze_arr2)

(2,)
[1 2]


In [34]:
y = np.array([1,2,3])
print(y.ndim)

# y = y.reshape((-1,1,1))
y = y.reshape((-1,1))
print(y.ndim)
print(y.shape)
print(y)

1
2
(3, 1)
[[1]
 [2]
 [3]]


In [38]:
a = np.array([1,2,3]) + 1
print(a)

b = np.array([[1],[2],[3]])
print(b)

c = a + b
print(c)

[2 3 4]
[[1]
 [2]
 [3]]
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [46]:
a = np.array([[2],[3],[4]])
print(a)
print(a.shape)

b = np.array([[1,4],[2,5],[3,6]])
print(b)
print(b.shape)

c = a + b
print(c)

[[2]
 [3]
 [4]]
(3, 1)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
[[ 3  6]
 [ 5  8]
 [ 7 10]]


In [43]:
a = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]])
print(a)

b = np.array([[1,4],[2,5]])
print(b)

c = a + b

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[[1 4]
 [2 5]]


ValueError: operands could not be broadcast together with shapes (4,5) (2,2) 

In [54]:
a = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8],[4,5,6,7,8,9]])
print(a)
print(a.shape)

b = np.array([[1,4],[2,5],[3,4],[4,5]])
print(b)
print(b.shape)

c =  a + b

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]]
(4, 6)
[[1 4]
 [2 5]
 [3 4]
 [4 5]]
(4, 2)


ValueError: operands could not be broadcast together with shapes (4,6) (4,2) 

In [53]:
a = np.array([[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8],[4,5,6,7,8,9]])
print(a)
print(a.shape)

b = np.array([[2],[3],[4],[5]])
# b = np.array([[1,4],[2,5],[3,4],[4,5]])
print(b)
print(b.shape)

c =  a + b
print(c)

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]]
(4, 6)
[[2]
 [3]
 [4]
 [5]]
(4, 1)
[[ 3  4  5  6  7  8]
 [ 5  6  7  8  9 10]
 [ 7  8  9 10 11 12]
 [ 9 10 11 12 13 14]]


In [56]:
A = np.array([[1,4],[2,5]])

# determine of a matrix
det_a = np.linalg.det(A)
print("determine of A =", det_a)

determine of A = -2.9999999999999996


In [59]:
B = np.array([[1,4,3],[2,5,4],[2,3,4]])

# determine of B matrix
det_b = np.linalg.det(B)
print("determine of A =", det_b)

determine of A = -4.0


In [62]:
A = np.array([[2, 1],[1, -1]])
B = np.array([5,1])

solutions = np.linalg.solve(A,B)
print("Solutions : ",solutions)

Solutions :  [2. 1.]


In [64]:
A = np.array([[3, 1, -2],[2, -1, 1],[1, 2, 3]])
B = np.array([9, 3, 12])

solutions = np.linalg.solve(A,B)
print("Solutions : ",solutions)

Solutions :  [2.6 3.2 1. ]


In [ ]:
#Generate a random number from 0 to 1
random_num = np.random.rand()
print(random_num)

#generate 5
random_num_1d= np.random.rand(5)
print(random_num_1d)

#ge
random_num2D = np.random.rand(3, 2)
print(random_num2D)

In [70]:
#
random_num = np.random.randint(1,10)
print(random_num)

random_num_1d= np.random.randint(1,10, size = 5)
print(random_num_1d)

random_num2D = np.random.randint(1, 10, size = (2,3))
print(random_num2D)

5
[1 2 9 5 5]
[[7 6 4]
 [7 1 8]]


In [76]:
random_num = np.random.choice([1,2,3,4,5])
print(random_num)

random_num_1d= np.random.choice([1,2,3,4,5], size = 3, replace = True)
print(random_num_1d)

random_num2D = np.random.choice([1,2,3,4,5], size = (2,3), replace = True)
print(random_num2D)

2
[3 1 2]
[[4 4 3]
 [5 4 4]]


### seed value is always 42
#### to repeat the same random number again and again

In [10]:
# import numpy as np

np.random.seed(42)
random_num = np.random.choice([1,2,3,4,5])
print(random_num)

np.random.seed(42)
random_num_again = np.random.choice([1,2,3,4,5])
print(random_num_again)

4
4
